- name: Playbook
  hosts: containers
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: yes